---
title: Hoplatools.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  forms:
    title: forms
    output: true
  gmail:
    title: gmail
    output: true
    permalink: gmail
theme: jekyll-theme-cayman
